export const StaticData = {
Meta_title:"Ryman stores in the UK | Ryman",
Meta_description:"Find your local Ryman store with our store locator. See opening times, directions and information for our stores across the UK.",
locator_breadcrumb:"Store Locator",
FindLocationtext:"Find a Location",
Usemylocation:"Use my location",
Search:"Search",
Brandname:"RYMAN",
miles:"miles",
tempClosed:"Temporarily Closed",
StoreDetailbtn:"View Store Detail",
Storehighlight:"Store Highlights",
Days:"Days",
Hours:"Hours",
Minutes:"Minutes",
Seconds:"Seconds",
getDirection:"Direction",
AllStores:"Ryman Stores in",
NearStoretext:"NEARBY LOCATIONS",
AllLocationtext:"View All Location",
PagenotFound:"404 - Page Not Found",
cantfind_page:"We're really sorry, we can't find the page you're looking for",
Youcouldtry:"You could try",
Previuspage:"Going back to the previous page",
homePage:"Going back to the homepage",
StoreFinder:"Store Finder",
FAQs:"FAQs",
DownloadApp:"Download Our App",
cookie:"our use of cookies",
CookiebuttonText:"Got IT",
Closed:"Closed",
DayofWeek:"Day of the Week",
Reopenmessage:"Message - The store is temporarily closed. It will reopen at",
Address:"Address",
Telephone:"Telephone",
Holdiay:"Holiday Hours",
}